version: 2

jobs:
  build:
    working_directory: ~/website
    docker:
      - image: yterajima/middleman:latest
        environment:
          TZ: Asia/Tokyo
          LANG: ja_JP.UTF-8
          MM_ENV: production
    steps:
      - checkout
      - run: mkdir -p ~/website/fillin/build
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run: |
          bundle install --path vendor/bundle
          npm install
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths: node_modules
      - run: NO_CONTRACTS=true bundle exec middleman build --build-dir ~/website/fillin/build
      - persist_to_workspace:
          root: fillin
          paths: build
  deploy:
    working_directory: ~/website
    docker:
      - image: yterajima/awscli:latest
        environment:
          TZ: Asia/Tokyo
          LANG: ja_JP.UTF-8
    steps:
      - attach_workspace:
          at: fillin
      - run: aws configure set preview.cloudfront true
      - run: ls -al fillin/build/
      - run: aws s3 sync fillin/build/ s3://$AWS_BUCKET --delete
      - run: sleep 5
      - run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths '/*'
      - run: curl http://www.google.com/webmasters/sitemaps/ping -k --verbose --get --data-urlencode "sitemap=https://www.fillin-inc.com/sitemap.xml"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
