version: 2.1

default: &default
  working_directory: ~/website
  docker:
    - image: ghcr.io/fillin-inc/middleman:3.0.2-slim-buster
      environment:
        TZ: Asia/Tokyo
        MM_ENV: production

orbs:
  slack: circleci/slack@4.4.2

jobs:
  release:
    <<: *default
    steps:
      - checkout
      - run: mkdir -p ~/website/fillin/build
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run: |
          bundle install --path vendor/bundle
          npm install
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: |
            NO_CONTRACTS=true bundle exec middleman build
            NO_CONTRACTS=true bundle exec middleman s3_sync
            sleep 5
            aws configure set preview.cloudfront true
            aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths '/*'
            curl http://www.google.com/webmasters/sitemaps/ping --get --data-urlencode "sitemap=https://www.fillin-inc.com/sitemap.xml"
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1

  build:
    <<: *default
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache-
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run: |
          bundle install --path vendor/bundle
          npm install
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: NO_CONTRACTS=true bundle exec middleman build

workflows:
  build-release:
    jobs:
      - release:
          filters:
            branches:
              only: main
  only-build:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
