name: Deploy to AWS S3

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v3
          with:
            node-version: .tool-versions
            cache: 'npm'

      - name: Build
        run:
          NO_CONTRACT=true bundle exec middleman build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: 'build/'
